name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  CI:
    name: CI
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      # Setup
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: docgpt
          environment-file: env.yaml
          python-version: 3.9
          auto-activate-base: false
      - run: |
          conda info
          conda list
      - name: Activate env
        run: |
             conda activate docgpt

      # Checks
      - name: linting
        run: |
          make pylint
      - name: formatting
        run: |
          make black-check
      - name: static typing
        run: |
          make mypy
      - name: test
        run: |
          make pytest
