name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: docgpt
          environment-file: env.yaml
          python-version: 3.9
          auto-activate-base: false
      - run: |
          conda info
          conda list

      - name: Activate env
        run: |
             conda activate docgpt
      #    - name: Set up Python environment
      #      uses: actions/setup-python@v2
      #      with:
      #        python-version: 3.9
      #    - name: Install Miniconda
      #      uses: swernst/install-miniconda@v1

      #    - name: Set up Conda
      #      uses: conda/setup-conda@v1
      #      with:
      #        python-version: 3.9

      #    - uses: conda-incubator/setup-miniconda@v2
      #        with:
      #          auto-update-conda: true
      #          python-version: ${{ matrix.python-version }}

#      - name: Activate env
#        run: |
#          conda env create -f env.yaml
#          conda activate docgpt
#          source ~/anaconda3/etc/profile.d/conda.sh
      #    - name: Activate Conda Environment
      #      run: conda activate docgpt

      - name: linting
        run: |
          make pylint
      - name: formatting
        run: |
          make black-check
      - name: static typing
        run: |
          make mypy
      - name: test
        run: |
          make pytest
